apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: sohit1991/orderapi:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
          limits:
            cpu: "500m"
        env: 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secrets
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mssql-secrets
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_PORT
        - name: SERVER
          value: mssql-service        

--- #api service

apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: LoadBalancer
  selector: 
    app: webapi
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080

