apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: sohit-k8s
spec:
  clusterIP: None
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
