#mssql base volume claim: mssql-base-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-base-volume
  namespace: sohit-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ms-storage

---
#mssql data volume claim: mssql-mdf-volume.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-mdf-volume
  namespace: sohit-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ms-storage

---
#mssql logs volume claim  mssql-ldf-volume

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-ldf-volume
  namespace: sohit-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi	  
  storageClassName: ms-storage